id: IDDFEA4D4
ocr_import_info:
  timestamp: '2023-10-06T15:22:15.156078+00:00'
  batch_id: batch-f535
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharmakyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-10-06 19:33:49.620110+00:00
last_modified: 2023-10-06 19:33:49.620118+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG5395
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG5395
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བྱང་སེམས་བློ་སྦྱོང་གི་རིམ་པ་གཅེས་བསྡུས་གཞན་ཕན་ཟླ་བའི་འོད་སྣང་།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9983401317125253
  ocr_word_median_confidence_index: 1.0
bases:
  I1KG5442:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5442
      total_pages: 378
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5442.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9983401317125253
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
